=== MAJD12358/GCD-PLUS/entities.dtd
<!ELEMENT Entities (Color, Font, Animation, Interaction, Security, AdvancedFeatures, Accessibility, Cloud, DevOps, Testing, FutureProofing, DeveloperTools, Documentation, License, Contributing, Configuration)>

<!ELEMENT Color (Red, Green, Blue)>
<!ELEMENT Red (#PCDATA)>
<!ELEMENT Green (#PCDATA)>
<!ELEMENT Blue (#PCDATA)>

<!ELEMENT Font (Family, Size)>
<!ELEMENT Family (#PCDATA)>
<!ELEMENT Size (#PCDATA)>

<!ELEMENT Animation (Rotate, Scale, Keyframe)>
<!ELEMENT Rotate (#PCDATA)>
<!ELEMENT Scale (#PCDATA)>
<!ELEMENT Keyframe (#PCDATA)>

<!ELEMENT Interaction (OnHover, OnClick)>
<!ELEMENT OnHover (#PCDATA)>
<!ELEMENT OnClick (#PCDATA)>

<!ELEMENT Security (Encrypt, Firewall)>
<!ELEMENT Encrypt (#PCDATA)>
<!ELEMENT Firewall (#PCDATA)>

<!ELEMENT AdvancedFeatures (ParallelProcessing, MachineLearning, AugmentedReality, BlockchainIntegration, QuantumComputing, NanoTechnologyIntegration, BrainComputerInterface)>
<!ELEMENT ParallelProcessing (#PCDATA)>
<!ELEMENT MachineLearning (#PCDATA)>
<!ELEMENT AugmentedReality (#PCDATA)>
<!ELEMENT BlockchainIntegration (#PCDATA)>
<!ELEMENT QuantumComputing (#PCDATA)>
<!ELEMENT NanoTechnologyIntegration (#PCDATA)>
<!ELEMENT BrainComputerInterface (#PCDATA)>

<!ELEMENT Accessibility (ScreenReaderSupport, KeyboardNavigation, VoiceControl, GestureRecognition, HapticFeedback)>
<!ELEMENT ScreenReaderSupport (#PCDATA)>
<!ELEMENT KeyboardNavigation (#PCDATA)>
<!ELEMENT VoiceControl (#PCDATA)>
<!ELEMENT GestureRecognition (#PCDATA)>
<!ELEMENT HapticFeedback (#PCDATA)>

<!ELEMENT Cloud (Storage, Database, Analytics, ServerlessComputing)>
<!ELEMENT Storage (#PCDATA)>
<!ELEMENT Database (#PCDATA)>
<!ELEMENT Analytics (#PCDATA)>
<!ELEMENT ServerlessComputing (#PCDATA)>

<!ELEMENT DevOps (VersionControl, ContinuousIntegration, Deployment, Monitoring)>
<!ELEMENT VersionControl (#PCDATA)>
<!ELEMENT ContinuousIntegration (#PCDATA)>
<!ELEMENT Deployment (#PCDATA)>
<!ELEMENT Monitoring (#PCDATA)>

<!ELEMENT Testing (UnitTesting, IntegrationTesting, PerformanceTesting, SecurityTesting)>
<!ELEMENT UnitTesting (#PCDATA)>
<!ELEMENT IntegrationTesting (#PCDATA)>
<!ELEMENT PerformanceTesting (#PCDATA)>
<!ELEMENT SecurityTesting (#PCDATA)>

<!ELEMENT FutureProofing (QuantumResistantEncryption, DecentralizedAI, EnergyEfficientComputing)>
<!ELEMENT QuantumResistantEncryption (#PCDATA)>
<!ELEMENT DecentralizedAI (#PCDATA)>
<!ELEMENT EnergyEfficientComputing (#PCDATA)>

<!ELEMENT DeveloperTools (IDE, Debugger, Profiler)>
<!ELEMENT IDE (#PCDATA)>
<!ELEMENT Debugger (#PCDATA)>
<!ELEMENT Profiler (#PCDATA)>

<!ELEMENT Documentation (Generate)>
<!ELEMENT Generate (#PCDATA)>

<!ELEMENT License (Type)>
<!ELEMENT Type (#PCDATA)>

<!ELEMENT Contributing (Guidelines)>
<!ELEMENT Guidelines (#PCDATA)>

<!ELEMENT Configuration (Load)>
<!ELEMENT Load (#PCDATA)>

=== MAJD12358/GCD-PLUS/entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Entities SYSTEM "entities.dtd">
<Entities>
  <Color>
    <Red>255</Red>
    <Green>255</Green>
    <Blue>255</Blue>
  </Color>

  <Font>
    <Family>Roboto</Family>
    <Size>24</Size>
  </Font>

  <Animation>
    <Rotate>360deg</Rotate>
    <Scale>1.2</Scale>
    <Keyframe>bounce 1s infinite</Keyframe>
  </Animation>

  <!-- واصل إضافة باقي العناصر والقيم هنا -->

</Entities>
